name: nicolena_dot_net
description: "Personal website of... well, you know who."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.1.0
  flutter_markdown: ^0.6.18+2
  go_router: ^12.1.1
  toml: ^0.15.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  parallax_rain: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:

  uses-material-design: true

  assets:
    - assets/asteroids_logo.png
    - assets/blog/BlogManifest.json

  fonts:
    - family: Hyperspace 
      fonts:
        - asset: assets/fonts/Hyperspace/Hyperspace.ttf
        - asset: assets/fonts/Hyperspace/HyperspaceItalic.ttf
          style: italic
        - asset: assets/fonts/Hyperspace/HyperspaceBold.ttf
          weight: 900 
    - family: ProFontIIx 
      fonts:
        - asset: assets/fonts/ProFont_NF/ProFontIIxNerdFont-Regular.ttf
          weight: 400
